### ISSUE TITLE
Load Pdf Files Directly

### ISSUE THREAD

**Issue by prometeomcclellan** [TakeshiOkamoto/PDFDesigner#1]
hello, is it posible to load files directly without the need to load them manually trough an input form?

**Comment by TakeshiOkamoto** [comment]
Hi.

Sorry, English can understand only 3-year-old level.

$B3N$+!"(BUint8Array$B$GFI$_9~$s$G$$$k$O$:$G$9$N$G!"(B
Uint8Array$B7A<0$G$"$l$P2?$G$b(BOK$B$G$9!#$?$V$s(B :-)

Anything is OK as long as it is Uint8Array object. maybe :-)

**Comment by prometeomcclellan** [comment]
ok, don´t worry, your library is amazing ! thanks for sharing this solution. I´ll find the way to resolve this issue. have a great one =)

**Comment by SalimCastellanos** [comment]
こんにちは、あなたはそれを使用する方法の例で私を助けることができた、例のリンクは動作しません、事前に助けてくれてありがとう。
Kon'nichiwa, anata wa sore o shiyō suru hōhō no rei de watashi o tasukeru koto ga dekita, rei no rinku wa dōsa shimasen, jizen ni tasukete kurete arigatō.

Hi, you could help me with an example of how to use it, the example links do not work, thank you in advance for the help.

**Comment by TakeshiOkamoto** [comment]
Sorry, We are currently unable to access the site because the server is down.

how to use
https://www.petitmonte.com/pdfdesigner/en/howto.html

Please wait for a while as the rental server is under recovery work.
