### ISSUE TITLE
PDF 1.5 and 1.6

### ISSUE THREAD

**Issue by bevrard** [TakeshiOkamoto/PDFDesigner#2]
Hi,

First of all, thanks for your library, it's amazing :-) !  
We are using it to split and merge a pdf.  Nevertheless we are facing issues with pdf in version 1.5 and 1.6 (1.4 and 1.7 are working well).

Do you know how we could fix issue for these versions? or is it possible to convert 1.5, 1.6 to 1.7 in javascript?

Thanks in advance

**Comment by TakeshiOkamoto** [comment]
[google translate]  
Sorry! English Can understand, only 3-year-old level.
---
This open source ported my library (Delphi language) created in 2003 to JavaScript.

So it corresponds to PDF 1.2 to PDF 1.4.
However, even if the version of PDF is written as 1.5 or later, it is possible to read if the inside of the file is 1.4 format.

"Deflate (ZIP compression)" is required to officially deal with PDF files of PDF 1.5 or later. For now, there is no plan to respond with this open source.

Conversion of PDF version can not be done unless Deflate is supported.

[Original text(Japanese)]
このオープンソースは2003年に作成した私のライブラリ(Delphi言語)をJavaScriptに移植しています。

ですので、当時のバージョンであるPDF1.2からPDF1.4迄に対応しています。
但し、PDFのバージョンが1.5以降と表記されていても、ファイル内部が1.4形式であれば読む事は可能です。

正式にPDF1.5以降のPDFファイルに対応するには「Deflate(ZIP圧縮)」が必要です。今の所、このオープンソースで対応する予定はありません。

PDFのバージョンを変換するにもDeflateに対応しないと出来ないです。

**Comment by bevrard** [comment]
Thanks for your support ! I'll investigate and reopen the ticket if I find something.

ありがとうございました :-)
