### ISSUE TITLE
How to Rotate PDF and Combine?

### ISSUE THREAD

**Issue by MuhShalah007** [TakeshiOkamoto/PDFDesigner#4]

**Comment by TakeshiOkamoto** [comment]
Combine rotation and coupling.

Supported files
Files that have been created at such as "Microsoft Office, OpenOffice and Chrome". Format is a file that conforms to the PDF1.4 format (such as ISO 19005-1). PDF1.5 later file can not be basically correspondence. but, can read if Internally PDF1.4 format.

How to use pdf-designer.js
https://www.petitmonte.com/pdfdesigner/en/howto.html

**Comment by MuhShalah007** [comment]
how to use it at once?

because when using rotation the pdf will be downloaded.

**Comment by TakeshiOkamoto** [comment]
excuse me.
I don't remember the source code.

It may be possible if you change the source code of the main body.

**Comment by MuhShalah007** [comment]
[#combine&rotate-pdf.html](https://github.com/MuhShalah007/PDFDesigner/blob/00093323890e4f0ed8713631ef3e2b5222b54fb5/examples/rotate%26combine-pdf.html#L72)
Solved thx
